export const FORM_STEPS = [
	{
		to: '/form/steps/01',
		meta: { title: 'Queixa Principal' },
		fields: [
			{ key: 'mainComplaint', name: 'Queixa Principal', type: 'text' },
			{
				key: 'lifeSatisfactionLevel',
				name: 'Satisfação com a vida',
				type: 'select',
			},
		],
	},
	{
		to: '/form/steps/02',
		meta: { title: 'Experiência ao Longo da Vida' },
		fields: [
			{ key: 'abandonment', name: 'Abandono', type: 'select' },
			{ key: 'sexualAbuse', name: 'Abusos Sexuais', type: 'select' },
			{ key: 'verbalAbuse', name: 'Abusos Verbais', type: 'select' },
			{ key: 'familyConflicts', name: 'Conflitos Familiares', type: 'select' },
			{ key: 'despair', name: 'Desespero', type: 'select' },
			{
				key: 'financialDifficulties',
				name: 'Dificuldades Financeiras',
				type: 'select',
			},
			{ key: 'humiliations', name: 'Humilhações', type: 'select' },
			{ key: 'trauma', name: 'Traumas', type: 'select' },
			{ key: 'violence', name: 'Violências', type: 'select' },
		],
	},
	{
		to: '/form/steps/03',
		meta: { title: 'Transtornos Atuais' },
		fields: [
			{ key: 'alcoholism', name: 'Alcoolismo', type: 'select' },
			{ key: 'anguish', name: 'Angústia', type: 'select' },
			{ key: 'anorexia', name: 'Anorexia', type: 'select' },
			{ key: 'anxiety', name: 'Ansiedade', type: 'select' },
			{
				key: 'generalizedAnxiety',
				name: 'Ansiedade Generalizada',
				type: 'select',
			},
			{ key: 'lowSelfEsteem', name: 'Autoestima Baixa', type: 'select' },
			{ key: 'borderline', name: 'Borderline', type: 'select' },
			{ key: 'bulimia', name: 'Bulimia', type: 'select' },
			{ key: 'burnout', name: 'Burnout', type: 'select' },
			{ key: 'excessiveJealousy', name: 'Ciúmes Excessivos', type: 'select' },
			{ key: 'bingeEating', name: 'Compulsão Alimentar', type: 'select' },
			{ key: 'sexualCompulsion', name: 'Compulsão Sexual', type: 'select' },
			{ key: 'depression', name: 'Depressão', type: 'select' },
			{ key: 'despair', name: 'Desespero', type: 'select' },
			{ key: 'erectileDysfunction', name: 'Disfunção Erétil', type: 'select' },
			{ key: 'financialScarcity', name: 'EScassez Financeira', type: 'select' },
			{ key: 'lackOfLibido', name: 'Falta de Libido', type: 'select' },
			{ key: 'phobias', name: 'Fobias', type: 'select' },
			{ key: 'failure', name: 'Fracasso', type: 'select' },
			{ key: 'frigidity', name: 'Frigidez', type: 'select' },
			{ key: 'insecurity', name: 'Insegurança', type: 'select' },
			{ key: 'fears', name: 'Medos', type: 'select' },
			{ key: 'moodSwing', name: 'Oscilações de Humor', type: 'select' },
			{ key: 'panic', name: 'Pânico', type: 'select' },
			{ key: 'uncontrolledAnger', name: 'Raiva Sem Controle', type: 'select' },
			{ key: 'remorse', name: 'Remorso', type: 'select' },
			{ key: 'feelingOfGuilt', name: 'Sentimento de Culpa', type: 'select' },
			{ key: 'loneliness', name: 'Solidão', type: 'select' },
			{ key: 'toc', name: 'TOC', type: 'select' },
			{ key: 'deepSadness', name: 'Tristeza Profunda', type: 'select' },
			{ key: 'shame', name: 'Vergonha', type: 'select' },
			{ key: 'bodyShame', name: 'Vergonha do Próprio Corpo', type: 'select' },
			{ key: 'drugAddictions', name: 'Vícios em Drogas', type: 'select' },
			{ key: 'gamingAddictions', name: 'Vícios em Jogos', type: 'select' },
		],
	},
	{
		to: '/form/steps/04',
		meta: { title: 'Corpo Físico' },
		fields: [
			{ key: 'allergies', name: 'Alergias', type: 'select' },
			{ key: 'skinDiseases', name: 'Doenças na Pele', type: 'select' },
			{ key: 'autoimmuneDiseases', name: 'Doenças Autoimune', type: 'select' },
			{ key: 'headache', name: 'Exaqueca', type: 'select' },
			{ key: 'fibromyalgia', name: 'Fibromialgia', type: 'select' },
		],
	},
	{
		to: '/form/steps/05',
		meta: { title: 'Medos Futuros' },
		fields: [
			{ key: 'abandonment', name: 'Abandono', type: 'select' },
			{ key: 'illnesses', name: 'Doenças', type: 'select' },
			{ key: 'death', name: 'Morte', type: 'select' },
			{ key: 'poverty', name: 'Pobreza', type: 'select' },
			{ key: 'loneliness', name: 'Solidão', type: 'select' },
			{ key: 'oldAge', name: 'Velhice', type: 'select' },
		],
	},
]
