import type { ThemeType } from '@/types'

export const lightTheme: ThemeType = {
	name: 'light',
	dark: false,
	variables: {
		'border-color': '#e5eaef',
		'border-opacity': 1,
	},
	colors: {
		primary: '#218CDE',
		secondary: '#49BEFF',
		info: '#539BFF',
		success: '#13DEB9',
		accent: '#FFAB91',
		warning: '#FFAE1F',
		error: '#FA896B',
		lightprimary: '#ECF2FF',
		lightsecondary: '#E8F7FF',
		lightsuccess: '#E6FFFA',
		lighterror: '#FDEDE8',
		lightinfo: '#EBF3FE',
		lightwarning: '#FEF5E5',
		textPrimary: '#2A3547',
		textSecondary: '#2A3547',
		borderColor: '#e5eaef',
		inputBorder: '#DFE5EF',
		containerBg: '#ffffff',
		background: '#ffffff',
		hoverColor: '#f6f9fc',
		surface: '#fff',
		'on-surface-variant': '#fff',
		grey100: '#F2F6FA',
		grey200: '#EAEFF4',
		grey400: '#7F8691',
	},
}
